### ISSUE TITLE
problem with --editable coveragepy

### ISSUE THREAD

**Issue by tarpas** [dougn/coverage_pth#1]
Hi and thanks for a nice solution!

Here are the steps to reproduce a problem which might be quite common:

```
hg clone https://bitbucket.org/ned/coveragepy

pip install --editable coveragepy

pip install coverage_pth

python

Traceback (most recent call last):
  File "/Users/tibor/.virtualenvs/test2/bin/../lib/python2.7/site.py", line 703, in <module>
    main()
  File "/Users/tibor/.virtualenvs/test2/bin/../lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/Users/tibor/.virtualenvs/test2/bin/../lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/tibor/.virtualenvs/test2/bin/../lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/tibor/.virtualenvs/test2/bin/../lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
ImportError: No module named coverage
```

**Comment by dougn** [comment]
Odd, when installed in editable form, I would have expected that coverage would still be usable as a module. That is kind of the point. I am not sure why it is not finding it (yet) at the site.py time. I think this is related to how pip manages the editable PYTHONPATH extensions.

**Comment by tarpas** [comment]
Yeah,

this works in the scenerio I described:
https://github.com/dougn/coverage_pth/compare/master...tarpas:563870fc9728281dc62eff24f468e1de828ec063

(naming the pth file az y0_coverage_pth.pth)

But it can't have coveragepy in install_requires ..

I'm not sure it's worth solving though.. see also:
https://bitbucket.org/ned/coveragepy/issue/367/automating-the-subprocess-measurement
