### ISSUE TITLE
Can't install - regular in setup.py has some problem

### ISSUE THREAD

**Issue by horejsek** [dougn/coverage_pth#2]
I wanted to install pytest-testmon which depends on this package and it fails to install it...

```
$ pip install coverage_pth
Downloading/unpacking coverage-pth
  Running setup.py egg_info for package coverage-pth
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/michal.horejsek/build/coverage-pth/setup.py", line 9, in <module>
        rel_site_packages = sprem.group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/michal.horejsek/build/coverage-pth/setup.py", line 9, in <module>

    rel_site_packages = sprem.group(1)

AttributeError: 'NoneType' object has no attribute 'group'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/michal.horejsek/build/coverage-pth
Storing complete log in /home/michal.horejsek/.pip/pip.log
```

**Comment by dougn** [comment]
What version of PIP/python are you using?

**Comment by dougn** [comment]
Looks like you are on an OSX machine, using a non-wheel supporting pip, and trying to install into the system python. When this is done, the site-packages directory is not one which can be accessed via relative setup path. The pattern match does not work against the '/Library/Python/<ver>/site-packages' directory we want to install into. Pip/setuptools does not allow for installing files via abspath for obvious security reasons.

I don't believe the wheel version will work properly either for installing into this system location.

It might be best to do this as a setuptools code execution on install, but the problem there is the 'no-side-effects' pip requirement for the next release of PIP/setuptools where all support for package code execution on install will be removed.

NOTE: I do not believe you WANT to install coverage_pth into the system python. This is generally a 'bad thing' to do as it imports and enables coverage on ALL python executions system wide. The design is to have this used with virtualenv under tighter control. The solution may be to have setup.py detect that it is trying to install into the system python and provide a clear error that this should never be done, and if you want to do this, learn how to do it by hand.

This will not fix the wheel problem.

**Comment by dougn** [comment]
The OSX system python with the supplied pip will install into 
/Library/Python/2.7/site-packages/
And load packages from:
/Library/Python/2.7/site-packages/
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/site-packages/

But not from:
/usr/lib/python2.7/site-packages/

Which exists, and is where the current OSX coverage_pth wheel installs coverage_pth.pth into, but is utterly ignored. As well as all the other files under /usr/lib/python2.7/; which begs the question of why they are on the system in the first place.

I do not want to break installing into a virtualenv on OSX. I do not see a good way of resolving this bug. the best I can do is make it raise an error, when building with setup tools, if it detects that it is being built for a system python on OSX. This will not solve the wheel bug on OSX which will allow a person to install the wheel on the system python on OSX, but that install will not be functional.

For your immediate problem, can you use virtualenv?

**Comment by horejsek** [comment]
Sorry for late reply. `pytest-testmon` removed dependency on this package so I haven't need it anymore. But more info so you can fix that for someone else is:

PIP version is 1.1 and Python 2.7. It's not on OS X, in fact on OS X it works just fine. :-) I'm trying to install it on 64bit Debian server with Linux core 3.18.19-zen.

**Comment by ryanhiebert** [comment]
I am seeing this issue on Ubuntu under PyPy. @dougn : If you are willing to merge and release a pull request to fix this, I'm inclined to do so. Or I can do more than that if you're willing to empower me in that way.
